/*
 * Scala.js (https://www.scala-js.org/)
 *
 * Copyright EPFL.
 *
 * Licensed under Apache License 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 */

package org.scalajs.testing.bridge

import scala.scalajs.js
import scala.scalajs.js.annotation._
import scala.scalajs.LinkingInfo
import scala.scalajs.LinkingInfo.linkTimeIf

/* Use the queue execution context (based on JS promises) explicitly:
 * We do not have anything better at our disposal and it is accceptable in
 * terms of fairness: JSRPC only handles in-between test communcation, so any
 * future chain will "yield" to I/O (waiting for a message) or an RPC handler in
 * a finite number of steps.
 */
import scala.scalajs.concurrent.JSExecutionContext.Implicits.queue

import org.scalajs.testing.common.RPCCore

/** JS RPC Core. */
private[bridge] final object JSRPC extends RPCCore {
  linkTimeIf(!LinkingInfo.targetPureWasm) {
    Com.init(handleMessage _)
  } {
    ()
  }

  def startIfPureWasm(): Unit = {
    linkTimeIf(LinkingInfo.targetPureWasm) {
      WasiDirectRpcTransport.init()

      var continue = true
      while (continue) {
        val msg = WasiDirectRpcTransport.pollNextMessage()
        if (msg == null) continue = false
        else handleMessage(msg)
      }
    } {
      ()
    }
  }

  /** The method referenced by the ScalajsCom.init function,
   *  whose real body is generated by the `wasmemitter.ClassEmitter#emitSpecialMethod`.
   *  This method is not intended to be used directly from a Scala program.
   */
  @noinline
  def handleMessage0(msg: String): Unit =
    handleMessage(msg)

  override protected def send(msg: String): Unit = {
    linkTimeIf(LinkingInfo.targetPureWasm) {
      WasiDirectRpcTransport.send(msg)
    } {
      Com.send(msg)
    }
  }

  @js.native
  @JSGlobal("scalajsCom")
  private object Com extends js.Object {
    def init(onReceive: js.Function1[String, Unit]): Unit = js.native
    def send(msg: String): Unit = js.native
    // We support close, but do not use it. The JS side just terminates.
    // def close(): Unit = js.native
  }
}
