package tanishiking:test@0.0.1;

world socket {
    import test;
    export wasi:cli/run@0.2.0;
}

world plug {
    export test;
}

interface test {
    add: func(a: s32, b: s32) -> s32;
    print-number: func(x: s32);

    say: func(content: string);

    parse: func(i: s32) -> tree;

    new-counter: func() -> counter;

    resource counter {
      // new: static func() -> counter; TODO: support static method
      up: func();
      down: func();
      value-of: func() -> s32;
    }

    variant tree {
      num-value(s32),
      float-value(f32),
      str-value(string),
    }

    // above max result (load from memory)
}
